# These are supported funding model platforms
github: [OFC-YOVANI]
patreon: # Replace 
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://youtu.be/AtI8nyBWrZk', 'https://github.com/OFC-YOVANI/HADES-BOT-OMEGA.git','https://boxmineworld.com']
